apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: nvidia-gpu
spec:
  amiSelectorTerms:
    - alias: al2@latest 
  role: karpenter-${cluster_name}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
  tags:
    karpenter.sh/discovery: ${cluster_name}

  # Enable the node "instance-store" ephemeral storage
  # https://karpenter.sh/docs/concepts/nodeclasses/#specinstancestorepolicy
  instanceStorePolicy: RAID0